version: '3'

services:
  caddy:
    build:
      context: ./dockerfile/caddy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./www:/srv
      - ./.caddy/data:/data
      - ./.caddy/config/:/config

  blog:
    image: coolrc/blog
    restart: unless-stopped
    volumes:
      - ./www:/blog/www
      - ./config:/blog/config

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: blog
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /root/pgdata:/var/lib/postgresql/data/pgdata
