# 重命名为config.yaml后可被载入
port: 80

db:
    host: 1.1.1.1
    port: 5432
    user: root
    password: password
    name: blog

user:
    username: root
    password: password

disqus:
    admin: root
    adminlabel: helloworld
    apikey: qwewq
    shortname: qwe
    sitename: qwe
sitename: helloworld
github: ""
author:
    name: coolrc
    email: root@coolrc.me
host: 'https://coolrc.me'
description: ''